spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/rating-db
    username: postgres
    password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/