spring:
  datasource:
    url: jdbc:postgresql://users-db-server:5432/users-db
    username: postgres
    password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/